drop table DIAGNOSIS;

* if (*{DBMS} == ORA)

-- Create table
create table DIAGNOSIS
(
  ID			NUMBER(18) not null,
  DIAG_CLASS_DOVA_CODE  VARCHAR(30) NOT NULL,
  DIAGNOSIS_CODE        VARCHAR(20) not null,
  CHAPTER		VARCHAR(1),
  PARENT_DIAGNOSIS_ID   NUMBER(18),
  HIDDEN		NUMBER(18) not null,
  DIAG_LEVEL_DOVA_CODE  VARCHAR(30),
  DIAG_CROSS_DOVA_CODE	VARCHAR(30),
  DELICACY_TYPE_DOVA_CODE VARCHAR(30),
  START_DATE		DATE NOT NULL,
  END_DATE		DATE,
  SYS_MODIFY_TIME	TIMESTAMP(6),
  SYS_VERSION		NUMBER(18),
  SYS_MODIFY_SID	NUMBER(18),
  SYS_MODIFY_UID	NUMBER(18),
  SYS_DELETE_STATUS	VARCHAR(1)
)
;

* end if

* if (*{DBMS} == SA)

-- Create table
create table DIAGNOSIS
(
  ID			BIGINT not null,
  DIAG_CLASS_DOVA_CODE  VARCHAR(30) NOT NULL,
  DIAGNOSIS_CODE        VARCHAR(20) not null,
  CHAPTER		VARCHAR(1),
  PARENT_DIAGNOSIS_ID   BIGINT,
  HIDDEN		BIGINT not null,
  DIAG_LEVEL_DOVA_CODE  VARCHAR(30),
  DIAG_CROSS_DOVA_CODE	VARCHAR(30),
  DELICACY_TYPE_DOVA_CODE VARCHAR(30),
  START_DATE		DATETIME NOT NULL,
  END_DATE		DATETIME,
  SYS_MODIFY_TIME	TIMESTAMP,
  SYS_VERSION		BIGINT,
  SYS_MODIFY_SID	BIGINT,
  SYS_MODIFY_UID	BIGINT,
  SYS_DELETE_STATUS	VARCHAR(1)
)
;

* end if

* if (*{DBMS} == MSS)

-- Create table
create table DIAGNOSIS
(
  ID			BIGINT not null,
  DIAG_CLASS_DOVA_CODE  VARCHAR(30) NOT NULL,
  DIAGNOSIS_CODE        VARCHAR(20) not null,
  CHAPTER		VARCHAR(1),
  PARENT_DIAGNOSIS_ID   BIGINT,
  HIDDEN		BIGINT not null,
  DIAG_LEVEL_DOVA_CODE  VARCHAR(30),
  DIAG_CROSS_DOVA_CODE	VARCHAR(30),
  DELICACY_TYPE_DOVA_CODE VARCHAR(30),
  START_DATE		DATETIME NOT NULL,
  END_DATE		DATETIME,
  SYS_MODIFY_TIME	DATETIME,
  SYS_VERSION		BIGINT,
  SYS_MODIFY_SID	BIGINT,
  SYS_MODIFY_UID	BIGINT,
  SYS_DELETE_STATUS	VARCHAR(1)
)
;

* end if

-- Create/Recreate primary key constraint 
alter table DIAGNOSIS  add constraint PK_DIAGNOSIS primary key (ID);

--* *DSV_SKIP_COLUMNS=ID
--\m diagnosis.dsv
